name: Build Zombicide Spawner APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixa o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Lista o conteúdo (útil para depuração)
      - name: List repository files
        run: ls -R

      # 3️⃣ Constrói o APK dentro do container oficial do Buildozer
      - name: Build with Buildozer (Docker)
        run: |
          docker run --rm -v "$(pwd)":/home/user/app kivy/buildozer buildozer android debug


      # 4️⃣ Publica o APK gerado
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SpawnMGR-apk
          path: Spawn_App/bin/*.apk
